### ISSUE TITLE
Invalid chat message transport

### ISSUE THREAD

**Issue by bluehenggege** [Synthintel0/MyGirlGPT#1]
I found that when there are many chat mssages, many old messages will not be sent to LLM due to the limitation of token.However, when calling GPT API in TelegramBot, all messages are sent in the past. 
I think it can be optimized to limit the number of sessions per transmission and reduce invalid transmission. I made some changes and will submit them later.

**Comment by Synthintel0** [comment]
That's cool. Thanks for your Contributing
