### ISSUE TITLE
Not receiving pictures from bot

### ISSUE THREAD

**Issue by Michael7575** [Synthintel0/MyGirlGPT#6]
I am not receiving any pictures from the bot. Below are my setups.
- Launch an instance on Runpod to host SD service API. Run in terminal `python launch.py --api --listen --share`. Retrieve the public url
- Create template per [here](https://github.com/Synthintel0/MyGirlGPT/tree/master/docker). I used the public url from above as SD_ADDRESS. Launch an instance on Runpod to host the TTS and LLM. 
- Interact with the bot on Telegram

**Comment by Synthintel0** [comment]
I just add example of how to test the sd webui. You can try if your SD_ADDRESS is right.
https://github.com/Synthintel0/MyGirlGPT/tree/master/example
