### ISSUE TITLE
Bot stuck on typing 

### ISSUE THREAD

**Issue by vishusinghal** [Synthintel0/MyGirlGPT#8]
The offical bot, as well as my deployment is stuck on _typing..._ message on telegram
![cherry](https://github.com/Synthintel0/MyGirlGPT/assets/3321872/0cba3b5a-a1d2-4148-ada5-8e512949ca71)

**Comment by Synthintel0** [comment]
This means mygirl do not get response from the LLM Server. You need to check the LLM Server.
About the offical bot, the LLM server has beed shut down.

**Comment by akmal02** [comment]
So your Telegram bot is just an experiment?  then you leave?  or maybe it is being repaired

**Comment by Synthintel0** [comment]
> So your Telegram bot is just an experiment? then you leave? or maybe it is being repaired
You can setup your bot @akmal02
